export const siteConfig = {
  // Change these values to personalize the complete site.
  girlfriendName: 'Her Name',
  birthdayDate: '2026-12-31T00:00:00+05:30',
  pin: '2580',
  senderName: 'Krishna',
  specialDate: '',
  heroMessage: 'A small corner of the internet made just to celebrate you and the moments that deserve to be remembered.',
  introLines: [
    "Today isn't just another day…",
    'Because someone genuinely special was born.',
  ],
  finalMessage: 'I hope this year brings you calm days, exciting beginnings, good people, and memories you will always want to keep.',
  letter: [
    'Happy Birthday.',
    'I wanted to make something that feels a little more personal than a normal message — something you could scroll through slowly and come back to whenever you wanted.',
    'Thank you for the conversations, the random moments, the laughs, and the kind of memories that become important without announcing themselves. I hope your day feels light, happy, and completely yours.',
    'Keep being curious, confident, and wonderfully yourself. There is a lot ahead of you, and I hope this next year gives you plenty of reasons to smile.',
  ],
  colors: {
    midnight: '#100a0e',
    burgundy: '#35131e',
    wine: '#5a2233',
    champagne: '#d6a475',
    ivory: '#f7efe8',
    rose: '#c77b88',
  },
  photos: {
    lockScreen: '/images/1000159749.webp',
    intro: '/images/1000159748.webp',
    hero: '/images/1000159716.webp',
    letter: '/images/1000159714.webp',
    gift: '/images/1000159715.webp',
    scratch: '/images/1000159747.webp',
    music: '/images/1000159713.webp',
    finale: '/images/1000159712.webp',
    timeline: [
      '/images/1000159748.webp',
      '/images/1000159747.webp',
      '/images/1000159715.webp',
      '/images/1000159713.webp',
    ],
    gallery: [
      '/images/1000159749.webp',
      '/images/1000159748.webp',
      '/images/1000159747.webp',
      '/images/1000159716.webp',
      '/images/1000159715.webp',
      '/images/1000159712.webp',
      '/images/1000159714.webp',
      '/images/1000159713.webp',
    ],
  },
  imagePositions: {
    '/images/1000159749.webp': '50% 26%',
    '/images/1000159748.webp': '50% 28%',
    '/images/1000159747.webp': '50% 22%',
    '/images/1000159716.webp': '50% 24%',
    '/images/1000159715.webp': '50% 24%',
    '/images/1000159712.webp': '50% 22%',
    '/images/1000159714.webp': '50% 24%',
    '/images/1000159713.webp': '50% 24%',
  },
  memories: [
    {
      date: 'A chapter worth keeping',
      title: 'The Beginning',
      description: 'Some memories become meaningful very quietly. They start as ordinary moments and later become the ones you remember most.',
      photo: '/images/1000159748.webp',
    },
    {
      date: 'One of those little moments',
      title: 'The Laughs In Between',
      description: 'Not every good memory needs a perfect plan. Sometimes the best ones are the random conversations and the unexpected smiles.',
      photo: '/images/1000159747.webp',
    },
    {
      date: 'A memory wall favorite',
      title: 'Your Energy',
      description: 'There is something memorable about the way you bring your own energy into a room — calm one moment, playful the next.',
      photo: '/images/1000159715.webp',
    },
    {
      date: 'Today',
      title: 'Your Day',
      description: 'A new year, a fresh chapter, and a whole collection of moments still waiting to happen.',
      photo: '/images/1000159713.webp',
    },
  ],
  appreciations: [
    { title: 'Your kindness', text: 'The small thoughtful things matter more than people realize — and you have a way of making them feel natural.' },
    { title: 'Your smile', text: 'It changes the mood of a moment without needing any explanation.' },
    { title: 'Your energy', text: 'There is a calm confidence in the way you carry yourself that makes ordinary moments feel a little more memorable.' },
    { title: 'Your support', text: 'Being there, listening, and caring in the little moments is something worth appreciating.' },
    { title: 'Your little habits', text: 'The tiny details are often what make someone unforgettable — the things nobody else would think to notice.' },
  ],
  quiz: [
    {
      question: 'Which chapter fits this memory best?',
      photo: '/images/1000159748.webp',
      options: ['The Beginning', 'The Finale', 'The Cake'],
      answer: 0,
    },
    {
      question: 'Which mood matches this photo?',
      photo: '/images/1000159716.webp',
      options: ['Golden-hour calm', 'Night-time magic', 'Rainy afternoon'],
      answer: 1,
    },
    {
      question: 'What matters most about a memory?',
      photo: '/images/1000159715.webp',
      options: ['Perfect lighting', 'How it made you feel', 'The camera'],
      answer: 1,
    },
  ],
  scratchMessage: 'A little reminder: you deserve a year full of moments that feel as good as your favorite memories.',
  giftMessage: 'One more wish for you: may this year surprise you in the best possible ways.',
  audio: {
    trackTitle: 'Your Song',
    artistName: 'Add your favorite track',
    audioFile: '', // Example: '/audio/song.mp3'
    coverPhoto: '/images/1000159713.webp',
  },
  voiceMessage: {
    title: 'A message from me',
    audioFile: '', // Example: '/audio/voice-message.mp3'
    photo: '/images/1000159712.webp',
  },
};
