import { lazy, Suspense, useEffect, useMemo, useRef, useState } from 'react';
import { motion } from 'framer-motion';
import { CakeSlice, Sparkles, Wind } from 'lucide-react';
import SectionHeading from '../components/SectionHeading';
const CakeScene=lazy(()=>import('../three/CakeScene'));

function supportsWebGL(){try{const c=document.createElement('canvas');return !!(window.WebGLRenderingContext&&(c.getContext('webgl')||c.getContext('experimental-webgl')))}catch{return false}}
function FallbackCake({done}){return <div className="grid h-full place-items-center bg-gradient-to-b from-[#2a1520] to-[#100a0e]"><motion.div animate={done?{scale:[1,1.08,1]}:{y:[0,-6,0]}} transition={{repeat:done?0:Infinity,duration:2.5}} className="text-center"><CakeSlice size={100} strokeWidth={1} className="mx-auto text-[#d6a475]"/><p className="mt-4 font-display text-2xl text-white">Birthday cake</p></motion.div></div>}
export default function CakeSection(){const [blow,setBlow]=useState(0);const [extinguished,setExtinguished]=useState(0);const timer=useRef(null);const webgl=useMemo(()=>supportsWebGL(),[]);const done=extinguished>=4;
  const start=()=>{if(done)return;timer.current=setInterval(()=>setBlow(v=>Math.min(100,v+5)),70)}; const stop=()=>{clearInterval(timer.current);timer.current=null;if(blow>20){setExtinguished(e=>Math.min(4,e+1));setBlow(0)}else setBlow(0)};
  useEffect(()=>()=>clearInterval(timer.current),[]);
  useEffect(()=>{if(blow>=100){clearInterval(timer.current);setExtinguished(e=>Math.min(4,e+1));setBlow(0)}},[blow]);
  return <section className="section-shell bg-[#100a0e]"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><SectionHeading eyebrow="Birthday ritual" title={done?'Wish made. Candles out.':'Make a wish.'} copy="Press and hold the button to blow out the candles. Each successful blow puts one candle out."/><div className="mt-10 overflow-hidden rounded-[32px] border border-white/10 bg-[#100a0e] shadow-2xl"><div className="relative h-[460px] sm:h-[560px]">{webgl?<Suspense fallback={<FallbackCake/>}><CakeScene extinguished={extinguished}/></Suspense>:<FallbackCake done={done}/>}<div className="pointer-events-none absolute inset-x-0 bottom-0 h-36 bg-gradient-to-t from-[#100a0e] to-transparent"/>{done&&<div className="confetti" aria-hidden="true">{Array.from({length:24},(_,i)=><i key={i} style={{'--i':i}}/>)}</div>}</div><div className="border-t border-white/10 p-5 sm:p-7"><div className="mx-auto max-w-xl text-center">{!done?<><div className="mb-4 h-2 overflow-hidden rounded-full bg-white/10"><motion.div className="h-full rounded-full bg-[#d6a475]" animate={{width:`${blow}%`}}/></div><button onPointerDown={start} onPointerUp={stop} onPointerLeave={stop} onKeyDown={e=>{if((e.key===' '||e.key==='Enter')&&!timer.current)start()}} onKeyUp={e=>{if(e.key===' '||e.key==='Enter')stop()}} className="premium-button mx-auto touch-none"><Wind size={17}/> Hold to blow · {4-extinguished} left</button></>:<div><Sparkles className="mx-auto mb-3 text-[#d6a475]"/><p className="font-display text-4xl text-white">Happy Birthday.</p><p className="mt-3 text-sm text-white/50">That wish is officially part of the story now.</p><button onClick={()=>setExtinguished(0)} className="mt-5 text-xs uppercase tracking-[.3em] text-[#d6a475]">Light them again</button></div>}</div></div></div></div></section>}
